# Generated by Django 3.2.21 on 2023-09-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessonvideo_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonvideo',
            name='Course',
        ),
    ]
