# Generated by Django 3.2.21 on 2023-09-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_lessonvideo_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
