# Generated by Django 3.2.21 on 2023-09-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notes_qanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='saved_id',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lessonvideo'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='choice',
            field=models.CharField(choices=[('course', 'course'), ('lesson', 'lesson'), ('video', 'video')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
