# Generated by Django 3.2.21 on 2023-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='saved_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
