# Generated by Django 4.0.3 on 2023-11-26 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_course_language_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarkCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('isBookmarked', models.BooleanField(default=False)),
                ('Bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
