# Generated by Django 4.0.3 on 2023-11-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bookmarkcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkcheck',
            name='Bookmark',
        ),
        migrations.AddField(
            model_name='bookmarkcheck',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
