# Generated by Django 4.0.3 on 2023-11-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_bookmarkcheck_bookmark_bookmarkcheck_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcheck',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.AddField(
            model_name='bookmarkcheck',
            name='lessonvideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lessonvideo'),
        ),
    ]
