# Generated by Django 4.0.3 on 2023-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bookmarkcheck_lesson_bookmarkcheck_lessonvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkcheck',
            old_name='type',
            new_name='types',
        ),
    ]
