# Generated by Django 4.0.3 on 2023-11-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_type_bookmarkcheck_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkcheck',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookmark'),
        ),
    ]
