# Generated by Django 4.0.3 on 2023-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bookmarkcheck_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
