# Generated by Django 4.0.3 on 2023-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_lessonvideo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
